# Generated by Django 6.0.3 on 2026-03-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertypage_bathrooms_propertypage_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypage',
            name='country',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='lga',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='state',
            field=models.CharField(max_length=160),
        ),
    ]
