# Generated by Django 6.0.3 on 2026-03-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertypage_country_alter_propertypage_lga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypage',
            old_name='lga',
            new_name='district',
        ),
    ]
