# Generated by Django 6.0.3 on 2026-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_lga_propertypage_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypage',
            name='offer',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('lease', 'Lease')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='size',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
